import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        // Các biến toàn cục từ thư viện ngoài hoặc file script khác
        askAI: "readonly",
        celebrate: "readonly",
        confetti: "readonly",
        firebase: "readonly",
        db: "readonly",
        closeStudentModal: "readonly",
        XLSX: "readonly",
        html2pdf: "readonly",
        router: "readonly",
        SoundManager: "readonly",
        Lesson: "readonly",
        ChoiceGame: "readonly",
        bootstrapEditor: "readonly",
        saveLessonToFirestore: "readonly",
        deleteLessonFromFirestore: "readonly",
        editExercise: "readonly",
        deleteExercise: "readonly",
        showTab: "readonly",
        addExercise: "readonly",
        openBulkGenerator: "readonly",
        saveBulkExercises: "readonly",
        closeBulkGenerator: "readonly",
        generateBulk: "readonly",
        editQuizItem: "readonly",
        deleteQuizItem: "readonly",
        addQuizItem: "readonly",
        openBulkQuizGenerator: "readonly",
        saveBulkQuiz: "readonly",
        closeBulkQuizGenerator: "readonly",
        generateBulkQuiz: "readonly",
        saveCurrentQuizItem: "readonly",
        submitMathLesson: "readonly",
        showMathFeedback: "readonly",
        GoogleGenAI: "readonly",
        toggleFullScreen: "readonly",
        toggleDarkMode: "readonly",
        submitLTVCUnified: "readonly",
        latTrangSoTay66: "readonly",
        capNhatBoDemChu73: "readonly",
        Quiz: "readonly",
        StarAdmin: "readonly"
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-useless-escape": "off",
      "no-useless-assignment": "off",
      "no-empty": "warn"
    },
  },
  {
    ignores: [
      "node_modules/",
      "dist/",
      "playwright-report/",
      "test-results/",
      ".vscode/",
      "_archive/",
      "js/**/*.js",
      "!js/data/vietnamese/3/*.js",
      "scripts/",
      "tests/",
      "sw.js",
    ],
  },
];
